extends Node

const property_nodes = {
	"null":preload("res://property_editor/property_containers/null.tscn"),
	"bool":preload("res://property_editor/property_containers/bool.tscn"),
	"int":preload("res://property_editor/property_containers/int.tscn"),
	"float":preload("res://property_editor/property_containers/float.tscn"),
	"string":preload("res://property_editor/property_containers/string.tscn"),
	"Vector2":preload("res://property_editor/property_containers/vec2.tscn"),
	"Vector3":preload("res://property_editor/property_containers/vec3.tscn"),
	"Rect2":preload("res://property_editor/property_containers/rect2.tscn"),
	"Transform2D":preload("res://property_editor/property_containers/transform2d.tscn"),
	"Color":preload("res://property_editor/property_containers/color.tscn"),
	"Dictionary":preload("res://property_editor/property_containers/dict.tscn"),
	"Array":preload("res://property_editor/property_containers/array.tscn"),
	"PoolByteArray":preload("res://property_editor/property_containers/poolbytearray.tscn"),
	"PoolIntArray":preload("res://property_editor/property_containers/poolintarray.tscn"),
	"PoolRealArray":preload("res://property_editor/property_containers/poolrealarray.tscn"),
	"PoolStringArray":preload("res://property_editor/property_containers/poolstringarray.tscn"),
	"PoolVector2Array":preload("res://property_editor/property_containers/poolvector2array.tscn"),
	"PoolVector3Array":preload("res://property_editor/property_containers/poolvector3array.tscn"),
	"PoolColorArray":preload("res://property_editor/property_containers/poolcolorarray.tscn"),
}
const supported_property_types = [
	"null",
	"bool",
	"int",
	"float",
	"string",
	"Vector2",
	"Rect2",
	"Vector3",
	"Transform2D",
	"Color",
	"Dictionary",
	"Array",
	"PoolByteArray",
	"PoolIntArray",
	"PoolRealArray",
	"PoolStringArray",
	"PoolVector2Array",
	"PoolVector3Array",
	"PoolColorArray",
]
const BUILTIN_TAGS = {
	"TAG_ALLOW_ACHIEVEMENTS":["bool",false,"Whether the mod would permit achievements.\nNot currently functional in-game."],
	"TAG_QOL":["bool",false,"Whether the mod adds QOL features."],
	"TAG_OVERHAUL":["bool",false,"Whether the mod overhauls a part or parts of the game."],
	"TAG_VISUAL":["bool",false,"Whether the mod makes visual adjustments."],
	"TAG_FUN":["bool",false,"Whether the mod is more fun than serious."],
	"TAG_UI":["bool",false,"Whether the mod adds UI elements."],
	"TAG_ADDS_SHIPS":["Array",[],"Names of ships that the mod adds.\nCan use translation strings."],
	"TAG_ADDS_EQUIPMENT":["Array",[],"Names of equipment that the mod adds.\nCan use translation strings."],
	"TAG_ADDS_GAMEPLAY_MECHANICS":["Array",[],"Names of gameplay mechanics that the mod adds.\nCan use translation strings."],
	"TAG_ADDS_EVENTS":["Array",[],"Names of events that the mod adds.\nCan use translation strings."],
	"TAG_HANDLE_EXTRA_CREW":["int",24,"For ships with very large numbers of crew, prevents derelict dialogue\nbeing broken if the crew count exceeds what the dialogue can handle.\n\nHevLib automatically sets this to 24, so only does anything above that."],
#	"TAG_USING_HEVLIB_RESEARCH":["array",[],""],
}
const property_assignment = {
	TYPE_NIL:"null",
	TYPE_BOOL:"bool",
	TYPE_INT:"int",
	TYPE_REAL:"float",
	TYPE_STRING:"string",
	TYPE_VECTOR2:"Vector2",
	TYPE_RECT2:"Rect2",
	TYPE_VECTOR3:"Vector3",
	TYPE_TRANSFORM2D:"Transform2D",
	TYPE_COLOR:"Color",
	TYPE_DICTIONARY:"Dictionary",
	TYPE_ARRAY:"Array",
	TYPE_RAW_ARRAY:"PoolByteArray",
	TYPE_INT_ARRAY:"PoolIntArray",
	TYPE_REAL_ARRAY:"PoolRealArray",
	TYPE_STRING_ARRAY:"PoolStringArray",
	TYPE_VECTOR2_ARRAY:"PoolVector2Array",
	TYPE_VECTOR3_ARRAY:"PoolVector3Array",
	TYPE_COLOR_ARRAY:"PoolColorArray",
}
